### ISSUE TITLE
Normalized Names

### ISSUE THREAD

**Issue by Scottz0r** [MatthewKing/IdentityWithoutEF#2]
Thanks for the example project. It helped me get a start.

However, I did eventually run into an issue with the normalized names. It seems that the normalized names are meant to be stored alongside of the non-normalized names. The following replaces the desired username casing with an all uppercase (default normalization):

```c#
public Task SetNormalizedUserNameAsync(ApplicationUser user, string normalizedName, CancellationToken cancellationToken)
{
    user.UserName = normalizedName;
    return Task.FromResult(true);
}
```

In addition, the Identity framework is using the normalized name to find existing values before adding a new user. When adding a new user, it will call `FindByNameAsync`, using the normalized user name to ensure the user name does not exist.

This is not a giant issue, but it can lead to some undesired/unclear behavior when getting into user roles and policies. The policy claim checking is case sensitive, so it may not be very apparent why a policy check is failing when generating claims from a ApplicationRole in this implementation. For example:

```C#
services.AddAuthorization(opt =>
{
    opt.AddPolicy("RequireAdministratorRole", policy => policy.RequireClaim(ClaimTypes.Role, "Administrator"));
});
```

This will fail because the claim is really "ADMINISTRATOR" in the claims identity.

**Comment by MatthewKing** [comment]
I'm glad you found the project helpful.

Thanks for the feedback, it raises some good points.
It's definitely doing the wrong thing at the moment.

My understanding is that the normalized fields really only exist for database performance reasons (so that you can stick a unique index on them to quickly check for duplicates etc.). See: http://stackoverflow.com/questions/41409692/what-is-the-use-of-normalized-email-username-in-net-core-identityuser-model and http://stackoverflow.com/questions/39651299/normalizedusername-vs-username-in-dotnet-core 

So I reckon this example project should just do the following (for each of the normalized fields)

- FindByNameAsync should do a case-insensitive search on Name.
- GetNormalizedNameAsync should return Name.ToUpper().
- SetNormalizedNameAsync should do nothing (or maybe even throw a NotImplementedException).

This should make it easy for basic users, and then more advanced users can make their own decisions re: support for database performance and indexing etc.

Does this make sense?

**Comment by Scottz0r** [comment]
To keep things simple, leaving SetNormalizedNameAsync empty and making a note about when to use NormalizedName might be the most clear. The current implementation `user.UserName = normalizedName;` doesn't seem correct because it's mixing the two concepts and removing desired name casing.

Throwing a NotImplementedException would not work because the framework calls SetNormalizedNameAsync when a user is created.

**Comment by MatthewKing** [comment]
Good point, that sounds like the best way to do it.
I'll make these changes in the next few days when I get some time.
When that's done, I'll close this issue.

Thanks so much for your feedback and advice.
